version: '3'
services:
  app:
    build:
      target: production
      context: .
    container_name: todo_app
    restart: always
    ports:
      - 8000:8000
#    volumes:
#      - ./:/todo_app
    environment:
      - MONGODB_CONN=mongodb://mongo
    env_file: .env
  mongo:
    image: mongo
    ports:
      - 27017:27017
