name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
    - run: docker build --target test --tag todo-app:test .
      name: build docker test image
    - run: docker run --env-file .env.test -p 8100:8100 todo-app:test
      name: run docker test image