name: Continuous Integration
on: 
  push:
    branches:    
    - main
    - 'releases/**'
    paths-ignore:
    - '**/README.md'
jobs:
      test:
          name: test
          runs-on: ubuntu-latest
          steps:
              - uses: actions/checkout@v3
              - uses: snyk/actions/python@master
#              - name: Run Snyk to check for vulnerabilities
                continue-on-error: true
                env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
              - run: docker build --target test --tag todo-app:test .
              - run: docker run --env-file .env.test -p 8100:8100 todo-app:test
  
      deploy:
          name: deploy
          needs: test
          runs-on: ubuntu-latest
          steps:
              - run: echo Publishing!
#              - uses: actions/checkout@v4
#              - name: login to docker
#              - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
#                with:
#                  username: ${{ secrets.DOCKER_USERNAME }}
#                  password: ${{ secrets.DOCKER_PASSWORD }}
#
#              - run: docker build --target test --tag todo-app:test .
#              - run: docker run --env-file .env.test -p 8100:8100 todo-app:test

