name: Continuous Integration
on: 
  push:
#    branches:    
#    - main
#    - 'Mod/**'
    paths-ignore:
    - '**/README.md'
env:
      # Use docker.io for Docker Hub if empty
      REGISTRY: docker.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: ${{ github.repository }}
jobs:
      test:
          name: test
          runs-on: ubuntu-latest
          steps:
              - uses: actions/checkout@v3
              - uses: snyk/actions/python@master
#              - name: Run Snyk to check for vulnerabilities
                continue-on-error: true
                env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
              - run: docker build --target test --tag todo-app:test .
              - run: docker run --env-file .env.test -p 5000:5000 todo-app:test
  
      deploy:
          name: deploy
          needs: test
          runs-on: ubuntu-latest
          steps:
              - run: echo Publishing!
              - uses: docker/setup-buildx-action@v2
#              - name: login to docker
              - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
                with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
#              - name: Extract metadata (tags, labels) for Docker
#                id: meta
#              - uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#                with:
#                  #images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#                  images: lvarnham/smellybeagle:latest
              
              - name: Build and push Docker image
                uses: docker/build-push-action@v2
                with:
                  #  context: "{{defaultContext}}"
                    push: true
                    tags: lvarnham/smellybeagle:latest
                    labels: production

              - run: docker build --target production --tag lvarnham:smellybeagle .
              - run: docker push lvarnham/smellybeagle:latest

